#!/usr/bin/env bash
# =============================================================================
# OmniAI v4 — One-Command Installer
# =============================================================================
# Usage: ./install.sh
# Options:
#   --reconfigure          Re-run full configuration
#   --reconfigure-keys     Re-enter API keys only
#   --update-token <NAME>  Update a specific token (e.g., GITHUB)
#   --help                 Show this help message
# =============================================================================

set -euo pipefail

# ── Colors ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# ── Helpers ───────────────────────────────────────────────────────────────────
print_header() {
  echo ""
  echo -e "${BOLD}${BLUE}╔══════════════════════════════════════════════════════════╗${NC}"
  echo -e "${BOLD}${BLUE}║           OmniAI v4 — Automated Installer                ║${NC}"
  echo -e "${BOLD}${BLUE}╚══════════════════════════════════════════════════════════╝${NC}"
  echo ""
}

step() {
  local num=$1
  local total=$2
  local msg=$3
  echo -e "\n${BOLD}${CYAN}[${num}/${total}]${NC} ${msg}"
}

success() {
  echo -e "  ${GREEN}✓${NC} $1"
}

warn() {
  echo -e "  ${YELLOW}⚠${NC}  $1"
}

error() {
  echo -e "  ${RED}✗${NC} $1" >&2
}

fatal() {
  echo -e "\n${RED}${BOLD}FATAL ERROR:${NC} $1" >&2
  echo -e "${YELLOW}See the Troubleshooting section in IMPLEMENTATION_GUIDE.md for help.${NC}" >&2
  exit 1
}

prompt_key() {
  local var_name=$1
  local display_name=$2
  local example=$3
  local current_val="${!var_name:-}"

  if [[ -n "$current_val" ]]; then
    echo -e "  ${GREEN}Already set:${NC} ${display_name} (${current_val:0:8}...)"
    return
  fi

  echo ""
  echo -e "  ${BOLD}${display_name}${NC}"
  echo -e "  Example format: ${YELLOW}${example}${NC}"
  read -r -p "  Paste your key here: " input_val

  if [[ -z "$input_val" ]]; then
    warn "${display_name} skipped — some features may not work."
  else
    export "${var_name}"="${input_val}"
    eval "${var_name}=\"${input_val}\""
  fi
}

write_env() {
  local env_file=".env"
  cat > "$env_file" << EOF
# OmniAI v4 — Environment Configuration
# Generated by install.sh on $(date)
# ⚠️  DO NOT COMMIT THIS FILE — it contains secrets

# ── AI Model Keys ─────────────────────────────────────────────────────────────
OPENAI_API_KEY=${OPENAI_API_KEY:-}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
GEMINI_API_KEY=${GEMINI_API_KEY:-}
PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY:-}

# ── GitHub ────────────────────────────────────────────────────────────────────
GITHUB_TOKEN=${GITHUB_TOKEN:-}

# ── Financial Integrations ────────────────────────────────────────────────────
EMPOWER_CLIENT_ID=${EMPOWER_CLIENT_ID:-}
EMPOWER_CLIENT_SECRET=${EMPOWER_CLIENT_SECRET:-}
MONARCH_TOKEN=${MONARCH_TOKEN:-}

# ── Hosting & Database ────────────────────────────────────────────────────────
VERCEL_TOKEN=${VERCEL_TOKEN:-}
SUPABASE_URL=${SUPABASE_URL:-}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-}

# ── App Settings ──────────────────────────────────────────────────────────────
NODE_ENV=production
APP_NAME=omni-ai-v4
EOF
  success ".env configuration file written"
}

# ── Parse arguments ───────────────────────────────────────────────────────────
RECONFIGURE=false
RECONFIGURE_KEYS=false
UPDATE_TOKEN=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --reconfigure)        RECONFIGURE=true; shift ;;
    --reconfigure-keys)   RECONFIGURE_KEYS=true; shift ;;
    --update-token)       UPDATE_TOKEN="${2:-}"; shift 2 ;;
    --help|-h)
      echo "Usage: ./install.sh [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --reconfigure          Re-run full configuration"
      echo "  --reconfigure-keys     Re-enter API keys only"
      echo "  --update-token <NAME>  Update a specific token"
      echo "  --help                 Show this help"
      exit 0
      ;;
    *) echo "Unknown option: $1. Use --help for usage."; exit 1 ;;
  esac
done

# ── Load existing .env if present ─────────────────────────────────────────────
if [[ -f ".env" ]] && [[ "$RECONFIGURE" == "false" ]]; then
  # shellcheck disable=SC1091
  set -a; source ".env" 2>/dev/null || true; set +a
fi

# =============================================================================
# MAIN INSTALLATION
# =============================================================================

print_header
TOTAL_STEPS=8

# ── Step 1: System requirements ───────────────────────────────────────────────
step 1 $TOTAL_STEPS "Checking system requirements..."

OS="$(uname -s)"
case "$OS" in
  Linux*)  PLATFORM="Linux" ;;
  Darwin*) PLATFORM="Mac" ;;
  CYGWIN*|MINGW*|MSYS*) PLATFORM="Windows" ;;
  *)       PLATFORM="Unknown" ;;
esac
success "Platform detected: ${PLATFORM}"

# Check bash version
BASH_MAJOR="${BASH_VERSINFO[0]:-0}"
if [[ "$BASH_MAJOR" -lt 4 ]]; then
  warn "Bash version ${BASH_VERSION} detected. Version 4+ is recommended."
  warn "On Mac: brew install bash"
fi
success "Bash ${BASH_VERSION}"

# ── Step 2: Install Node.js ───────────────────────────────────────────────────
step 2 $TOTAL_STEPS "Checking Node.js installation..."

if command -v node &>/dev/null; then
  NODE_VERSION=$(node --version)
  # Extract major version number
  NODE_MAJOR="${NODE_VERSION#v}"
  NODE_MAJOR="${NODE_MAJOR%%.*}"
  if [[ "$NODE_MAJOR" -ge 18 ]]; then
    success "Node.js ${NODE_VERSION} — OK"
  else
    warn "Node.js ${NODE_VERSION} found, but v18+ is required. Attempting upgrade..."
    install_node
  fi
else
  warn "Node.js not found. Installing..."
  install_node
fi

install_node() {
  if command -v brew &>/dev/null; then
    brew install node@20 &>/dev/null && success "Node.js installed via Homebrew"
  elif command -v apt-get &>/dev/null; then
    curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - &>/dev/null
    sudo apt-get install -y nodejs &>/dev/null && success "Node.js installed via apt"
  else
    fatal "Cannot automatically install Node.js on your system.\nPlease install it manually from https://nodejs.org then re-run this script."
  fi
}

# Check npm
if command -v npm &>/dev/null; then
  NPM_VERSION=$(npm --version)
  success "npm ${NPM_VERSION} — OK"
else
  fatal "npm not found. Please install Node.js from https://nodejs.org"
fi

# ── Step 3: Install project dependencies ─────────────────────────────────────
step 3 $TOTAL_STEPS "Installing project dependencies..."

if [[ ! -f "package.json" ]]; then
  # Create a minimal package.json if one doesn't exist yet
  cat > package.json << 'PKGJSON'
{
  "name": "omni-ai-v4",
  "version": "4.0.0",
  "description": "OmniAI v4 — Multi-model AI orchestration platform",
  "private": true,
  "scripts": {
    "start": "node config/setup-ai-keys.js",
    "verify": "node scripts/verify.js",
    "setup:keys": "node config/setup-ai-keys.js",
    "setup:github": "node config/setup-github.js",
    "setup:vercel": "node config/setup-vercel.js",
    "setup:supabase": "node config/setup-supabase.js",
    "setup:siri": "node config/setup-siri.js"
  },
  "dependencies": {
    "dotenv": "^16.4.5",
    "openai": "^4.47.1",
    "@anthropic-ai/sdk": "^0.20.9",
    "@google/generative-ai": "^0.11.0",
    "@supabase/supabase-js": "^2.43.0",
    "node-fetch": "^3.3.2"
  },
  "engines": {
    "node": ">=18.0.0"
  }
}
PKGJSON
  success "package.json created"
fi

echo "  Installing packages (this may take 1–2 minutes)..."
if npm install --silent 2>/dev/null; then
  success "All dependencies installed"
else
  warn "npm install had warnings — checking critical packages..."
  # Try installing just the essentials
  npm install dotenv openai @anthropic-ai/sdk @google/generative-ai @supabase/supabase-js 2>/dev/null || \
    fatal "Failed to install dependencies. Check your internet connection and try again."
fi

# ── Step 4: Collect API keys ──────────────────────────────────────────────────
step 4 $TOTAL_STEPS "Setting up your configuration..."

if [[ "$RECONFIGURE_KEYS" == "true" ]] || [[ "$RECONFIGURE" == "true" ]] || [[ -z "${OPENAI_API_KEY:-}" ]]; then
  echo ""
  echo -e "  ${BOLD}You'll need to paste your API keys below.${NC}"
  echo -e "  ${YELLOW}Keys are only stored locally in your .env file — never sent anywhere.${NC}"
  echo ""

  # AI Keys
  echo -e "  ${BOLD}── AI Model Keys ──────────────────────────${NC}"
  prompt_key "OPENAI_API_KEY"      "OpenAI (ChatGPT) API Key"      "sk-proj-abc123..."
  prompt_key "ANTHROPIC_API_KEY"   "Anthropic (Claude) API Key"    "sk-ant-abc123..."
  prompt_key "GEMINI_API_KEY"      "Google Gemini API Key"         "AIzaSyabc123..."
  prompt_key "PERPLEXITY_API_KEY"  "Perplexity AI API Key"         "pplx-abc123..."

  # GitHub
  echo ""
  echo -e "  ${BOLD}── GitHub ──────────────────────────────────${NC}"
  prompt_key "GITHUB_TOKEN" "GitHub Personal Access Token" "ghp_abc123..."

  # Financial (optional)
  echo ""
  echo -e "  ${BOLD}── Financial Integrations (optional — press Enter to skip) ──${NC}"
  prompt_key "EMPOWER_CLIENT_ID"     "Empower Client ID"     "empower-client-id..."
  prompt_key "EMPOWER_CLIENT_SECRET" "Empower Client Secret" "empower-secret..."
  prompt_key "MONARCH_TOKEN"         "Monarch Money Token"   "monarch-token-abc..."

  # Hosting
  echo ""
  echo -e "  ${BOLD}── Hosting & Database ──────────────────────${NC}"
  prompt_key "VERCEL_TOKEN"              "Vercel Token"              "vercel-token-abc..."
  prompt_key "SUPABASE_URL"             "Supabase Project URL"      "https://abc.supabase.co"
  prompt_key "SUPABASE_ANON_KEY"        "Supabase Anon Key"         "eyJhbGci..."
  prompt_key "SUPABASE_SERVICE_ROLE_KEY" "Supabase Service Role Key" "eyJhbGci..."

  write_env
else
  success "Existing configuration loaded from .env"
fi

# Handle --update-token flag
if [[ -n "$UPDATE_TOKEN" ]]; then
  echo ""
  echo -e "  ${BOLD}Updating token: ${UPDATE_TOKEN}${NC}"
  case "$UPDATE_TOKEN" in
    GITHUB)    prompt_key "GITHUB_TOKEN" "GitHub Personal Access Token" "ghp_abc123..." ;;
    OPENAI)    prompt_key "OPENAI_API_KEY" "OpenAI API Key" "sk-proj-abc123..." ;;
    ANTHROPIC) prompt_key "ANTHROPIC_API_KEY" "Anthropic API Key" "sk-ant-abc123..." ;;
    GEMINI)    prompt_key "GEMINI_API_KEY" "Google Gemini API Key" "AIzaSy..." ;;
    PERPLEXITY) prompt_key "PERPLEXITY_API_KEY" "Perplexity API Key" "pplx-..." ;;
    VERCEL)    prompt_key "VERCEL_TOKEN" "Vercel Token" "vercel-..." ;;
    SUPABASE)
      prompt_key "SUPABASE_URL" "Supabase URL" "https://abc.supabase.co"
      prompt_key "SUPABASE_ANON_KEY" "Supabase Anon Key" "eyJhbGci..."
      prompt_key "SUPABASE_SERVICE_ROLE_KEY" "Supabase Service Role Key" "eyJhbGci..."
      ;;
    *) warn "Unknown token name: ${UPDATE_TOKEN}. Valid names: GITHUB, OPENAI, ANTHROPIC, GEMINI, PERPLEXITY, VERCEL, SUPABASE" ;;
  esac
  write_env
fi

# ── Step 5: Set up Supabase database ─────────────────────────────────────────
step 5 $TOTAL_STEPS "Setting up Supabase database..."

if [[ -n "${SUPABASE_URL:-}" ]] && [[ -n "${SUPABASE_SERVICE_ROLE_KEY:-}" ]]; then
  if node config/setup-supabase.js 2>/dev/null; then
    success "Supabase database configured"
  else
    warn "Supabase setup encountered issues — check your credentials and try again"
    warn "You can re-run database setup with: node config/setup-supabase.js"
  fi
else
  warn "Supabase credentials not provided — skipping database setup"
  warn "You can set this up later by running: ./install.sh --reconfigure"
fi

# ── Step 6: Validate AI connections ──────────────────────────────────────────
step 6 $TOTAL_STEPS "Validating AI model connections..."

validate_ai() {
  local name=$1
  local key_var=$2
  local key_val="${!key_var:-}"

  if [[ -z "$key_val" ]]; then
    warn "${name}: No key provided — skipped"
    return
  fi

  if node -e "
    require('dotenv').config();
    process.env['${key_var}'] = '${key_val}';
    // Simple key format check
    const key = process.env['${key_var}'];
    if (!key || key.length < 10) { process.exit(1); }
    console.log('key_ok');
  " 2>/dev/null | grep -q "key_ok"; then
    success "${name}: Key format looks valid ✓"
  else
    warn "${name}: Key may be invalid — double-check at your provider dashboard"
  fi
}

validate_ai "OpenAI"     "OPENAI_API_KEY"
validate_ai "Anthropic"  "ANTHROPIC_API_KEY"
validate_ai "Gemini"     "GEMINI_API_KEY"
validate_ai "Perplexity" "PERPLEXITY_API_KEY"
validate_ai "GitHub"     "GITHUB_TOKEN"

# ── Step 7: Deploy to Vercel ──────────────────────────────────────────────────
step 7 $TOTAL_STEPS "Deploying to Vercel..."

if [[ -z "${VERCEL_TOKEN:-}" ]]; then
  warn "Vercel token not provided — skipping deployment"
  warn "You can deploy later by running: node config/setup-vercel.js"
  DEPLOY_URL="Not deployed (add VERCEL_TOKEN to .env)"
elif command -v npx &>/dev/null; then
  if node config/setup-vercel.js 2>/dev/null; then
    # Read the deployed URL if the script writes it
    DEPLOY_URL=$(cat .deploy-url 2>/dev/null || echo "Check Vercel dashboard")
    success "Deployed to Vercel: ${DEPLOY_URL}"
  else
    warn "Vercel deployment encountered issues"
    warn "Re-run: node config/setup-vercel.js"
    DEPLOY_URL="Deployment pending — check Vercel dashboard"
  fi
else
  warn "npx not available — skipping Vercel deployment"
  DEPLOY_URL="Run manually: node config/setup-vercel.js"
fi

# ── Step 8: Final verification ────────────────────────────────────────────────
step 8 $TOTAL_STEPS "Running final verification..."

PASS_COUNT=0
FAIL_COUNT=0

check_item() {
  local label=$1
  local key_var=$2
  if [[ -n "${!key_var:-}" ]]; then
    success "${label}"
    (( PASS_COUNT++ )) || true
  else
    warn "${label} — not configured"
    (( FAIL_COUNT++ )) || true
  fi
}

check_item "OpenAI (ChatGPT)"     "OPENAI_API_KEY"
check_item "Anthropic (Claude)"   "ANTHROPIC_API_KEY"
check_item "Google Gemini"        "GEMINI_API_KEY"
check_item "Perplexity AI"        "PERPLEXITY_API_KEY"
check_item "GitHub"               "GITHUB_TOKEN"
check_item "Supabase database"    "SUPABASE_URL"
check_item "Vercel hosting"       "VERCEL_TOKEN"
check_item "Empower (financial)"  "EMPOWER_CLIENT_ID"
check_item "Monarch (financial)"  "MONARCH_TOKEN"

# =============================================================================
# SUMMARY
# =============================================================================

echo ""
echo -e "${BOLD}${BLUE}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${BLUE}║                  Installation Complete                   ║${NC}"
echo -e "${BOLD}${BLUE}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

if [[ $FAIL_COUNT -eq 0 ]]; then
  echo -e "  ${GREEN}${BOLD}🎉 All systems configured and ready!${NC}"
else
  echo -e "  ${YELLOW}${BOLD}✓ Core setup complete — ${PASS_COUNT} integrations active, ${FAIL_COUNT} skipped${NC}"
fi

echo ""
echo -e "  ${BOLD}Your OmniAI v4 is available at:${NC}"
echo -e "  ${CYAN}${DEPLOY_URL}${NC}"
echo ""
echo -e "  ${BOLD}Quick commands:${NC}"
echo -e "  ${YELLOW}./install.sh --reconfigure-keys${NC}  Re-enter API keys"
echo -e "  ${YELLOW}./install.sh --reconfigure${NC}       Full reconfiguration"
echo -e "  ${YELLOW}./install.sh --update-token GITHUB${NC} Update a single token"
echo ""
echo -e "  ${BOLD}Need help?${NC}"
echo -e "  Read: ${CYAN}IMPLEMENTATION_GUIDE.md${NC} → Section 14 (Troubleshooting)"
echo -e "  Open issue: ${CYAN}https://github.com/paulglasow/omni-ai-automation/issues${NC}"
echo ""